name: Publish package to GitHub Packages 
 
on: 
  workflow_run: 
    workflows: ["CI / Build & Test"] 
    types: 
      - completed 
 
jobs: 
  publish: 
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    runs-on: ubuntu-latest 
    permissions: 
      contents: read 
      packages: write 
 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4 
 
      - name: Setup .NET 
        uses: actions/setup-dotnet@v3 
        with: 
          dotnet-version: '8.0.x' 
 
      - name: Restore 
        run: dotnet restore 
 
      - name: Build (Release) 
        run: dotnet build -c Release --no-restore 
 
      - name: Pack 
        run: dotnet pack Todo.Core/Todo.Core.csproj -c Release -o ./artifacts 
 
      - name: List artifacts 
        run: ls -la ./artifacts || true 
 
      - name: Push package to GitHub Packages (NuGet) 
        run: dotnet nuget push ./artifacts/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate 
